### ISSUE TITLE
Rules won't sign into a DSM using a port other than 443

### ISSUE THREAD

**Issue by marknca** [deep-security/aws-config#1]
A Marketplace AMI or on-premises installation of Deep Security uses port 4119 by default. Rules should allow for a dsPort rule parameter to be passed

**Comment by glb** [comment]
Given the size restrictions on rule parameters (256 characters maximum for the entire JSON-encoded object), how about just supporting `dsHost` with a `:port` tacked on the end?

**Comment by marknca** [comment]
Resolved with commit https://github.com/deep-security/aws-config/commit/075fcc4ce7bf968514404c46515b197adc898b23.
