### ISSUE TITLE
Unable to use these config rules with DSM 10.

### ISSUE THREAD

**Issue by abhinav-badola** [deep-security/aws-config#5]
I followed the procedure mentioned, but unable to connect to DSM 10 using these libraries. Can you please let us know if there is a new version of Config rules which are compatible with DSM 10. I also tried Python SDK from https://github.com/deep-security/deep-security-py

Got connectivity to trendmicro but the SDK is not documented well. So i don't know how to call different functions and what are the parameters required or optional. what is the return types, etc. Looking to build config rules to check if instances are protected by trendmicro with which all services enabled, Health of Instances (Alerts), etc.

**Comment by marknca** [comment]
The issue appears to be that the rules were using an older version of the deep-securit-py project. I've merged in the new version (fully compatible with Deep Security 10) and made some tweaks.

No functionality or configuration changes, just make sure you update the AWS Lambda function to use the new library (a/k/a re-deploy). 

The code is currently in [the ds10 branch](https://github.com/deep-security/aws-config/tree/ds10). If it works for you, I'll merge it into master.

**Comment by abhinav-badola** [comment]
![image](https://user-images.githubusercontent.com/1751007/28836895-141b943c-76eb-11e7-929b-eac8e1f51f54.png)
I am getting this error when running the lambda function now. I tried dsIsInstanceProtectedByAntiMalware function with DS10 branch

**Comment by marknca** [comment]
Hmm, that's interesting. It _could_ be due to a non-ASCII character (cyrillic, arabic, emoji, etc.) in either the username, password, or tenant name. The simplest way to check is locally.

If you have the repo cloned or downloaded on your system, you can do the following from the local python 2.7 interpreter (type ```python``` at the command line in the aws-config/ folder):

```
import deepsecurity
mgr = deepsecurity.dsm.Manager(username="YOUR_USERNAME", password="YOUR_PASSWORD", tenant="YOUR_TENANTNAME", hostname="YOUR_DSM_DOMAIN")
# if you don't need tenant or hostname, just leave them out
mgr.sign_in()
mgr.computers.get()
print len(mgr.computers)
mgr.sign_out()
```

That should either produce an error after ```mgr.sign_in()``` or display the number of computers that Deep Security currently knows about. It'll be easier to troubleshoot from here.

**Comment by marknca** [comment]
Based on our chat (offline), added support for two new rule parameters;

- dsPort
- dsIgnoreSslValidation

These will allow you to connect to any DSM even if it's using a self-signed SSL certificate

**Comment by abhinav-badola** [comment]
works if i add port='443', ignore_ssl_validation=True in parameters of
mgr = deepsecurity.dsm.Manager(username="YOUR_USERNAME", password="YOUR_PASSWORD", tenant="YOUR_TENANTNAME", hostname="YOUR_DSM_DOMAIN")

**Comment by abhinav-badola** [comment]
I get the same error if i pass on credentials via parameters of config:
Could not authenticate to Deep Security. Threw exception: decoding Unicode is not supported

But if i hardcode the credentials in lambda itself. I get another error after signing in, which i figured out when using the new SDK from https://github.com/deep-security/deep-security-py which doesn't have  a function get_computers_with_details in Manager:


07:28:31
[2017-08-02 07:28:31]	SSL certificate validation has been disabled for this call

07:28:32
[2017-08-02 07:28:32]	Failed to make SOAP POST call [authenticate] Threw exception:

07:28:32
HTTP Error 500: Internal Server Error

07:28:32
[2017-08-02 07:28:32]	SSL certificate validation has been disabled for this call

07:28:33
[2017-08-02 07:28:33]	Failed to make REST POST call [authentication/login/primary] Threw exception:

07:28:33
HTTP Error 403: Forbidden

07:28:33
'Manager' object has no attribute 'get_computers_with_details': AttributeError Traceback (most recent call last): File "/var/task/dsIsInstanceProtectedByAntiMalware.py", line 170, in aws_config_rule_handler mgr.get_computers_with_details() AttributeError: 'Manager' object has no attribute 'get_computers_with_details'
'Manager' object has no attribute 'get_computers_with_details': AttributeError
Traceback (most recent call last):
File "/var/task/dsIsInstanceProtectedByAntiMalware.py", line 170, in aws_config_rule_handler
mgr.get_computers_with_details()
AttributeError: 'Manager' object has no attribute 'get_computers_with_details'

**Comment by marknca** [comment]
Ok, the _unicode_ issue was tied to a change in how AWS Config Rules passed along the rule parameters. They are passing them as a full unicode strings, the script (in ```deep-security-py```) was trying to double convert them.

That issue is fixed within the current version of ```deep-security-py``` (updated in this repo on the /ds10 branch).

I also ran down some additional issues with the DS10 API changes that were popping up. These consisted mainly of naming problems. During the course of that work, more logging statements were added so that CloudWatch logs provides much more granular information (see attached pic).

![screen shot 2017-08-02 at 2 44 11 pm](https://user-images.githubusercontent.com/39484/28889145-1839aaee-7791-11e7-82a1-0f232ff25d16.png)

**Comment by abhinav-badola** [comment]
I ran into another issue with the latest commit from you.
when I pass the parameters from Config rule, I get 
`decoding Unicode is not supported: TypeError
Traceback (most recent call last):
File "/var/task/dsIsInstanceProtectedByAntiMalware.py", line 159, in aws_config_rule_handler
ds_hostname = unicode(event['ruleParameters']['dsHostname'], "utf-8") if event['ruleParameters'].has_key('dsHostname') else None
TypeError: decoding Unicode is not supported`

![image](https://user-images.githubusercontent.com/1751007/28911997-a4bff558-7832-11e7-9dd4-737ea6f5a734.png)

But when i hard coded the credentials again in lambda function and commented line 158-161
I ran into another error, seems like use of anothe old SDK function: 
`'Computer' object has no attribute 'cloud_instance_id': AttributeError
Traceback (most recent call last):
File "/var/task/dsIsInstanceProtectedByAntiMalware.py", line 174, in aws_config_rule_handler
if details.cloud_instance_id and (details.cloud_instance_id.lower().strip() == instance_id.lower().strip()):
AttributeError: 'Computer' object has no attribute 'cloud_instance_id'`

![image](https://user-images.githubusercontent.com/1751007/28912095-10e5abce-7833-11e7-8f93-579b223c2058.png)

Regards,
Abhinav Badola

**Comment by marknca** [comment]
These were errors corrected in dsIsInstanceProtectedBy.py but not yet pushed to the other rules. Fixed in https://github.com/deep-security/aws-config/commit/145b327663ece6bb64290d94d6addaba3067c00c

**Comment by marknca** [comment]
Resolved with commit https://github.com/deep-security/aws-config/commit/075fcc4ce7bf968514404c46515b197adc898b23.

**Comment by abhinav-badola** [comment]
Thanks Mark

**Comment by tatyany** [comment]
Implementing TrendMicro Deep Security automation with AWS GuardDuty (https://github.com/deep-security/amazon-guardduty) and receiving a similar error:

2018-10-03

16:06:08
START RequestId: 3a1e7877-c726-11e8-be8b-0506d40e6563 Version: $LATEST

16:06:08
Processing Amazon GuardDuty event of type [UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration]

16:06:09
[2018-10-03 16:06:09]	Failed to make SOAP POST call [authenticateTenant] Threw exception:

16:06:09
HTTP Error 500:

16:06:11
[2018-10-03 16:06:11]	Failed to make REST POST call [authentication/login] Threw exception:

16:06:11
HTTP Error 403:

16:06:11
[2018-10-03 16:06:11]	Failed to make SOAP POST call [hostDetailRetrieve] Threw exception:

16:06:11
HTTP Error 500:

16:06:11
[2018-10-03 16:06:11]	Failed to make SOAP POST call [securityProfileRetrieveAll] Threw exception:

16:06:11
HTTP Error 500:

16:06:11
Signed into Deep Security
Signed into Deep Security

16:06:11
To enable Slack functionality, add the 'SlackURL' environment variable with the value set to the incoming webhook URL for your desired team/channel

16:06:11
END RequestId: 3a1e7877-c726-11e8-be8b-0506d40e6563

16:06:11
REPORT RequestId: 3a1e7877-c726-11e8-be8b-0506d40e6563	Duration: 2845.21 ms	Billed Duration: 2900 ms Memor

Running 'import deepsecurity.....' from the local python 2.7 interpreter produces the same errors. Are any updates to the repo required to support current version of DSM?
